name: GitVersion CheckOut 
description: Checks out a project and runs GitVersion 

runs: 
  using: "composite"
  steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0  
    - name: Install Gitversion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'
    - name: Determine Version 
      uses: gittools/actions/gitversion/execute@v3.1.1
      with:
        useConfigFile: true
    - name: Run GitVersion 
      shell: cmd 
      run: dotnet-gitversion /output buildserver